# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    text.search_filter:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments: [ { name: 'ipartial' } ]
        tags:      [ { name: 'api_platform.filter', id: 'text.search' } ]
